### PR TITLE
routers- login- register - users

### PR DESCRIPTION
**Pull request by Kevin962022**

### CODE REVIEW

**Review by erickact — COMMENTED** [review]
Change length of service_status in models.py

**Review by erickact — CHANGES_REQUESTED** [review]
please change this code: length=5 in service_status (model.py)

**Review by MaguiSanchez — CHANGES_REQUESTED** [review]
Change length of service_status in models.py - line 105

**Review by erickact — APPROVED** [review]
ok

**Review by MaguiSanchez — APPROVED** [review]

**Pull request merged**
